name: Security Pipeline (DevSecOps)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  sast:
    name: 1. Static Analysis (SAST)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Bandit
      run: pip install bandit
    - name: Run Bandit Scan
      run: bandit -r . -x ./venv,./.github

  sca:
    name: 2. Dependency Checker (SCA)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install pip-audit
      run: pip install pip-audit
    - name: Run Dependency Scan
      run: pip-audit -r requirements.txt || true

  dast:
    name: 3. Dynamic Analysis (DAST)
    runs-on: ubuntu-latest
    # Этот шаг запустится, только если прошли тесты SAST и SCA (для экономии ресурсов)
    needs: [sast, sca]
    if: always() 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run FastAPI Application in Background
      # Запускаем uvicorn на порту 8000 в фоне
      run: |
        uvicorn app.main:app --host 127.0.0.1 --port 8000 &
        sleep 5 # Даем серверу 5 секунд на запуск и инициализацию БД

    - name: Install Nikto DAST Scanner
      run: sudo apt-get update && sudo apt-get install -y nikto

    - name: Run DAST Scan with Nikto
      run:  nikto -h http://127.0.0.1:8000 -Plugins "outdated;httpoptions;tests" -Format html -output dast_report.html

    - name: Upload DAST Report Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dast-security-report
        path: dast_report.html